[files]
extend-exclude = ["CHANGELOG.md", "Cargo.lock"]

[default]
extend-ignore-words-re = [
  "^[A-Za-z]{1,3}$", # Ignore short words
]
extend-ignore-identifiers-re = [
  "^[A-Za-z]{1,3}$", # Ignore short identifiers
]
